# Generated by Django 4.1.2 on 2022-10-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=100)),
                ('mythic', models.CharField(max_length=100)),
                ('boots', models.CharField(max_length=100)),
                ('legendary_1', models.CharField(max_length=100)),
                ('legendary_2', models.CharField(max_length=100)),
                ('legendary_3', models.CharField(max_length=100)),
                ('legendary_4', models.CharField(max_length=100)),
            ],
        ),
    ]
